### ISSUE TITLE
defaults for unset variables

### ISSUE THREAD

**Issue by zhammer** [gobuffalo/helpers#16]
i'd like to do something like `<title><%= title or "My Website" %></title>` so that if I don't set a title in a handler, the page's title will be "My Website". If I do `c.Set("title", "Messages")`, the title will be "Messages".

is there a way to set a default for an unset variable? it seems like referencing an unset name breaks the page with `"title": unknown identifier`

**Comment by paganotoni** [comment]
Added `default` helper. Thanks @zhammer
